### ISSUE TITLE
Unable to find javascript files

### ISSUE THREAD

**Issue by jamesw** [igorkasyanchuk/new_ckeditor#4]
Fantastic gem, thank you. I would like to use it in my CMS and I have added //= link new_ckeditor/classic/ckeditor.js
 to the manifest.js but I am told The asset "new_ckeditor/classic/ckeditor.js" is not present in the asset pipeline
So I have looked for the javascript files and they are not present anywhere. I am obviously missing something.
I ran the new_ckeditor generator which generated the views fine
So where do the javascript file live please?

**Comment by igorkasyanchuk** [comment]
Hello,
Files are here https://github.com/igorkasyanchuk/new_ckeditor/tree/master/app/assets/javascripts/new_ckeditor/balloon for example

**Comment by igorkasyanchuk** [comment]
Let me know if you have other questions, also I've a sample app
